In [1]:
import numpy as np

# Example 3x3 matrix (3 products × sales data)
# Each row represents a different product
sales_data = np.array([
    [100, 150, 200],
    [80, 120, 160],
    [90, 110, 130]
])

# Calculate average price of all products sold
average_price = np.mean(sales_data)

print("Sales Data:\n", sales_data)
print("\nAverage price of all products sold:", round(average_price, 2))

Sales Data:
 [[100 150 200]
 [ 80 120 160]
 [ 90 110 130]]

Average price of all products sold: 126.67
